//Cafe Actions
export const FETCH_CAFE_BY_ID = 'FETCH_CAFE_BY_ID';
export const FETCH_CAFE_BY_ID_SUCCESS = 'FETCH_CAFE_BY_ID_SUCCESS';
export const FETCH_CAFE_BY_ID_FAILURE = 'FETCH_CAFE_BY_ID_FAILURE';
export const FETCH_CAFES = 'FETCH_CAFES';
export const FETCH_CAFES_SUCCESS = 'FETCH_CAFES_SUCCESS';
export const FETCH_CAFES_FAILURE = 'FETCH_CAFES_FAILURE';
export const UPDATE_CAFE = 'UPDATE_CAFE';
export const UPDATE_CAFE_SUCCESS = 'UPDATE_CAFE_SUCCESS';
export const UPDATE_CAFE_FAILURE = 'UPDATE_CAFE_FAILURE';
export const ADD_CAFE = 'ADD_CAFE';
export const ADD_CAFE_SUCCESS = 'ADD_CAFE_SUCCESS';
export const ADD_CAFE_FAILURE = 'ADD_CAFE_FAILURE';
export const DELETE_CAFE = 'DELETE_CAFE';
export const DELETE_CAFE_SUCCESS = 'DELETE_CAFE_SUCCESS';
export const DELETE_CAFE_FAILURE = 'DELETE_CAFE_FAILURE';

//Employee Actions
export const FETCH_EMPLOYEE_BY_ID = 'FETCH_EMPLOYEE_BY_ID';
export const FETCH_EMPLOYEE_BY_ID_SUCCESS = 'FETCH_EMPLOYEE_BY_ID_SUCCESS';
export const FETCH_EMPLOYEE_BY_ID_FAILURE = 'FETCH_EMPLOYEE_BY_ID_FAILURE';
export const FETCH_EMPLOYEES = 'FETCH_EMPLOYEES';
export const FETCH_EMPLOYEES_SUCCESS = 'FETCH_EMPLOYEES_SUCCESS';
export const FETCH_EMPLOYEES_FAILURE = 'FETCH_EMPLOYEES_FAILURE';
export const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE';
export const UPDATE_EMPLOYEE_SUCCESS = 'UPDATE_EMPLOYEE_SUCCESS';
export const UPDATE_EMPLOYEE_FAILURE = 'UPDATE_EMPLOYEE_FAILURE';
export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const ADD_EMPLOYEE_SUCCESS = 'ADD_EMPLOYEE_SUCCESS';
export const ADD_EMPLOYEE_FAILURE = 'ADD_EMPLOYEE_FAILURE';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';
export const DELETE_EMPLOYEE_SUCCESS = 'DELETE_EMPLOYEE_SUCCESS';
export const DELETE_EMPLOYEE_FAILURE = 'DELETE_EMPLOYEE_FAILURE';